# Generated by Django 5.0.3 on 2024-06-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('ranking_id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100, unique=True)),
                ('total_calories_burned', models.FloatField()),
            ],
        ),
    ]
