# Generated by Django 5.0.3 on 2024-06-25 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_profile_daily_consumedcalorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('ranking_id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100, unique=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('total_calories_burned', models.FloatField(default=0)),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='accounts.profile')),
            ],
        ),
    ]
