# Generated by Django 5.0.3 on 2024-06-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='rank',
        ),
        migrations.AlterField(
            model_name='ranking',
            name='nickname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
