# Generated by Django 5.0.3 on 2024-06-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
