# Generated by Django 5.0.3 on 2024-06-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_daily_consumedcalorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickName',
            field=models.TextField(max_length=30, unique=True),
        ),
    ]
