# Generated by Django 5.0.3 on 2024-06-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickName',
            field=models.TextField(max_length=30),
        ),
    ]
