# Generated by Django 5.0.3 on 2024-06-22 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calorie', models.FloatField()),
                ('end_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_visits', to='main.building')),
                ('start_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_visits', to='main.building')),
            ],
        ),
    ]
